compatibility_date = "2022-01-18"
name = "listening-game"
type = "javascript"

zone_id = ""
account_id = "f7f8cd27de762723b14dab4fb54a5337"
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build"

[build.upload]
format="service-worker"
